# Generated by Django 6.0.2 on 2026-02-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('FOOD', 'Food'), ('TRAVEL', 'Travel'), ('HOUSING', 'Housing'), ('UTILITIES', 'Utilities'), ('HEALTH', 'Health'), ('EDUCATION', 'Education'), ('MISC', 'Miscellaneous')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('ONE', 'One-Time'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=10)),
            ],
        ),
    ]
