# Generated by Django 6.0.2 on 2026-02-26 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='name',
            new_name='expense_name',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='type',
            new_name='expense_type',
        ),
    ]
